name: Go Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Add Go bin to PATH
        run: echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV

      - name: Run tests with JUnit output
        run: gotestsum --junitfile test-results.xml -- ./...

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
        if: always() # Upload test results even if tests fail
